### PR TITLE
Use latest nrfxlib

### PR DESCRIPTION
**Pull request by jonathanpallant**

### CODE REVIEW

**Comment by huntc** [comment]
Hi @jonathanpallant - thanks so much for providing this repo as an example.

I've been trying to build this branch on my macOS machine. Unfortunately I see:

```
% cargo build --release --features=nrf9160dk
   Compiling version_check v0.9.3
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v1.0.26
   Compiling typenum v1.13.0
   Compiling unicode-xid v0.2.1
   Compiling libc v0.2.94
   Compiling memchr v2.3.4
   Compiling log v0.4.14
   Compiling stable_deref_trait v1.2.0
   Compiling cfg-if v1.0.0
   Compiling cortex-m v0.7.2
   Compiling glob v0.3.0
   Compiling syn v1.0.71
   Compiling nb v1.0.0
   Compiling vcell v0.1.3
   Compiling void v1.0.2
   Compiling bitflags v1.2.1
   Compiling bitfield v0.13.2
   Compiling unicode-width v0.1.8
   Compiling cortex-m-rt v0.6.13
   Compiling cortex-m v0.6.7
   Compiling regex-syntax v0.6.23
   Compiling r0 v0.2.2
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling bindgen v0.56.0
   Compiling vec_map v0.8.2
   Compiling nrf9160-pac v0.2.1
   Compiling termcolor v1.1.2
   Compiling humantime v2.1.0
   Compiling shlex v0.1.1
   Compiling lazycell v1.3.0
   Compiling fpa v0.1.0
   Compiling lazy_static v1.4.0
   Compiling rustc-hash v1.1.0
   Compiling peeking_take_while v0.1.2
   Compiling cc v1.0.67
   Compiling rand_core v0.5.1
   Compiling nrf9160-hal v0.10.0 (https://github.com/nrf-rs/nrf52-hal?rev=9a0ea11#9a0ea11a)
   Compiling heapless v0.5.6
   Compiling byteorder v1.4.3
   Compiling panic-halt v0.2.0
   Compiling menu v0.2.1
   Compiling spin v0.5.2
   Compiling libloading v0.7.0
   Compiling volatile-register v0.2.0
   Compiling nb v0.1.3
   Compiling textwrap v0.11.0
   Compiling semver v0.9.0
   Compiling generic-array v0.14.4
   Compiling nom v5.1.2
   Compiling clang-sys v1.2.0
   Compiling embedded-hal v0.2.4
   Compiling hash32 v0.1.1
   Compiling rustc_version v0.2.3
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv8m.main-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `log`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

However, I do have the target installed:

```
% rustup target add thumbv8m.main-none-eabi
info: component 'rust-std' for target 'thumbv8m.main-none-eabi' is up to date
```

Any thoughts? My rust environment should be quite updated. Is this project/branch still building for you?

**Comment by jonathanpallant** [comment]
What is the output of `rustc --version`?

**Comment by huntc** [comment]
> rustc --version

```
% rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by jonathanpallant** [comment]
You may need to tell Cargo to use the new 1.51+ resolver, to solve Cargo issue https://github.com/rust-lang/cargo/issues/5730. See https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2.

Edit: Because what I think is happening is that one of the crates used as a build-dependency is opting into a feature that requires `libstd`. Before "resolver 2" was added, Cargo couldn't tell dependency features and build features apart, meaning that `libstd` was then required for your embedded build.

**Pull request closed without merging**
